FROM golang:1.25.1-alpine3.22 AS builder

ENV GO111MODULE=on
ENV CGO_ENABLED=0

WORKDIR /app

COPY cmd ./cmd
COPY docs ./docs
COPY internal ./internal
COPY go.mod go.sum main.go ./

RUN go mod tidy
RUN go build -o /go/bin/go-backend-tmpl

FROM alpine:latest

RUN apk add --no-cache tzdata

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENV TZ=Asia/Shanghai

# RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
# ENV TZ=UTC

WORKDIR /app

COPY --from=builder /go/bin/go-backend-tmpl /app/go-backend-tmpl

EXPOSE 8080

# CMD ["/app/go-backend-tmpl", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

# docker buildx build --platform linux/amd64 -t go-backend-tmpl:latest .
# docker run -d -p 8080:8080 --env-file api.env --name go-backend-tmpl -t go-backend-tmpl:latest /app/go-backend-tmpl server start --host 0.0.0.0 --port 8080